# This is for non-development Conda packages.
# (Development-only packages are specified in .devcontainer/dev-conda-environment.yaml.)

name: base
channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - streamlit
  - torch
  - torchvision
  - numpy
  - pillow
  - pandas
  - matplotlib
  - scikit-learn
  - streamlit-drawable-canvas
platforms:
- linux-64
- linux-aarch64
