# This is for starting the non-development Docker container.

version: '3.9'

services:
  app:
    build:
      context: .
    ports:
    - 8501:8501
    environment:
    - TZ=Europe/Berlin
    command: streamlit run python/digit_classifier_app/app.py
